### ISSUE TITLE
使用泛化调用的场景，注册发现无法正常工作

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/dubbo-servicecomb#130]

**Comment by zhaozw** [comment]
简单说一下问题和解决思路：
RegistrationListener.processNewSubscriberEvent方法会查找泛化调用的微服务，泛化访问的URL如下
consumer://10.69.34.249/org.apache.dubbo.rpc.service.GenericService?application=cse-v2-consumer&category=providers,configurators,routers&check=false&dubbo=2.0.2&generic=true&init=false&interface=com.huaweicloud.api.ProviderService&pid=17396&release=2.7.15&side=consumer&sticky=false&timestamp=1645405274320
但是这里面是找不到的，这个泛化其实是和interface参数的微服务一一对应的，此处是com.huaweicloud.api.ProviderService

RegistrationListener.instancesToURLs方法里面会根据schemaInfos向notifyUrls里面添加key，value（是个URL列表），这里如果不添加org.apache.dubbo.rpc.service.GenericService，后面泛化调用的时候找不到对应的org.apache.dubbo.rpc.Invoker，所以这里也要做处理，
每个schema都额外针对泛化做一次处理，value列表里面的URL值类似如下：
dubbo://10.69.34.249:8085/com.huaweicloud.api.ProviderService?anyhost=true&application=cse-v2-provider&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.huaweicloud.api.ProviderService&methods=sayHello&pid=18408&release=2.7.15&service.name=ServiceBean:/com.huaweicloud.api.ProviderService&side=provider&timestamp=1644565441839


测试场景，用了2个GenericService，这两个泛化都是由一个服务器的provider提供的，又测试一下从consumer调用2个不同的provider的GenericService，都正常通过测试
