### ISSUE TITLE
dubbo治理规则动态更新，事件监听不稳定，统一事件监听整改

### ISSUE THREAD

**Issue by develpoerX** [huaweicloud/dubbo-servicecomb#86]

**Comment by liubao68** [comment]
1. 没有实现动态配置监听
2. 配置监听的事件是全量配置项，而不是变化配置项，导致删除配置的时候，配置仍然生效
3. 处理配置变更为空的时候， 初始化为 emptyMap， 导致后续新的配置来临的时候，无法修改，抛出异常。
