### ISSUE TITLE
dubbo服务发现支持接口新增修改版本号多个版本并存的场景

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/dubbo-servicecomb#90]

**Comment by liubao68** [comment]
测试场景：provider 版本v1有一个接口；版本v2有二个接口. v1/v2两个版本并存的时候， 调用会失败。

**Comment by develpoerX** [comment]
此问题已经解决。多版本并存，接口相同时，根据负载均衡策略调用。dubbo自身机制通过在接口服务定义中指定的consumer和provider版本解决这个问题。但是这样在下面的业务场景中存在一些问题：比如，provider服务v1版本的A接口有a()方法，provider服务v2版本的A接口有a()，b()方法。某个注册中心有100个provider实例节点，provider版本V1有90个，10个provider版本V2.现有consumer存在调用A.a()和A.b()情况，如果在接口中直接指定版本会导致所有访问流量都到10个V2版本的节点。
有个优化点：
就是在dubbo的负载均衡处理点进行扩展，每次接口调用时，通过负载均衡策略会选出一个provider,此时先对选出的provider进行判断是否存在本次调用的方法。若不存在重新选取，否则进行下一步处理。这样可以充分利用其它节点。

**Comment by liubao68** [comment]
这个需求先关闭，不解决。
